
//API1
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam_richard",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}

###
// User indormation
//API 1 SCenerio2
POST http://localhost:3000/register
Content-Type: application/json

{
 "username": "Johny",
  "name": "Peter John",
  "password": "rich@1234",
  "gender": "Female",
  "location": "Dallas"
}

###
// login user
//API 2 SCenerio1
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam_richad",
  "password": "richard_568"
}

###
// Change Password
//API 3 SCenerio1
PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_5",
  "newPassword": "richard@123"
}
